;; Felon staking - stake STX, earn rewards
(define-constant err-owner-only (err u100))
(define-constant err-staking-paused (err u101))
(define-constant err-below-min (err u102))
(define-constant err-insufficient-stake (err u103))
(define-constant err-lock-not-expired (err u104))
(define-constant err-zero-amount (err u105))
(define-constant err-no-rewards (err u106))
(define-constant err-already-inited (err u107))

(define-constant min-stake-amount u1000000)
(define-constant lock-period u100)
(define-constant scale u1000000000000)

(define-data-var total-staked u128 u0)
(define-data-var reward-per-share u128 u0)
(define-data-var total-rewards-added u128 u0)
(define-data-var staking-paused bool false)
(define-data-var owner (optional principal) none)

(define-map stakes
  { staker: principal }
  { amount: u128, reward-debt: u128, staked-at-block: uint }
)

(define-private (get-owner) (unwrap-panic (var-get owner)))

(define-private (update-reward-per-share (new-rewards u128))
  (let ((total (var-get total-staked)))
    (if (<= total u0)
      (var-set total-rewards-added (+ (var-get total-rewards-added) new-rewards))
      (let ()
        (var-set total-rewards-added (+ (var-get total-rewards-added) new-rewards))
        (var-set reward-per-share (+ (var-get reward-per-share) (/ (* new-rewards scale) total)))
      )
    )
  )
)

(define-private (pending-rewards (staker principal))
  (let ((entry (map-get? stakes { staker: staker })))
    (if (is-none entry) u0
      (let ((u (unwrap-panic entry)))
        (let ((amt (get amount u)) (debt (get reward-debt u)) (acc (var-get reward-per-share)))
          (if (< (* amt acc) debt) u0 (- (/ (* amt acc) scale) debt))
        )
      )
    )
  )
)

(define-public (init)
  (asserts! (is-none (var-get owner)) err-already-inited)
  (var-set owner (some (tx-sender)))
  (ok true)
)

(define-public (stake (amount u128))
  (let ((caller (contract-caller)))
    (asserts! (not (var-get staking-paused)) err-staking-paused)
    (asserts! (>= amount min-stake-amount) err-below-min)
    (asserts! (> amount u0) err-zero-amount)
    (let ((entry (map-get? stakes { staker: caller })))
      (let ((cur (default-to { amount: u0, reward-debt: u0, staked-at-block: block-height } entry)))
        (let ((pending (pending-rewards caller))
              (new-amount (+ (+ (get amount cur) amount) pending)))
          (var-set total-staked (+ (- (var-get total-staked) (get amount cur)) new-amount))
          (map-set stakes { staker: caller }
            { amount: new-amount, reward-debt: (/ (* new-amount (var-get reward-per-share)) scale), staked-at-block: (get staked-at-block cur) }
          )
          (ok true)
        )
      )
    )
  )
)

(define-public (unstake (amount u128))
  (let ((caller (contract-caller)))
    (asserts! (not (var-get staking-paused)) err-staking-paused)
    (asserts! (> amount u0) err-zero-amount)
    (let ((entry (map-get? stakes { staker: caller })))
      (asserts! (is-some entry) err-insufficient-stake)
      (let ((info (unwrap-panic entry)))
        (let ((user-amt (get amount info)) (staked-at (get staked-at-block info)))
          (asserts! (>= user-amt amount) err-insufficient-stake)
          (asserts! (>= block-height (+ staked-at lock-period)) err-lock-not-expired)
          (let ((pending (pending-rewards caller)))
            (if (> pending u0) (try! (as-contract (stx-transfer? pending (tx-sender) caller))) (ok u0))
          )
          (let ((new-amount (- user-amt amount)))
            (var-set total-staked (- (var-get total-staked) amount))
            (if (<= new-amount u0) (map-delete stakes { staker: caller })
              (map-set stakes { staker: caller }
                { amount: new-amount, reward-debt: (/ (* new-amount (var-get reward-per-share)) scale), staked-at-block: block-height }
              )
            )
            (try! (as-contract (stx-transfer? amount (tx-sender) caller)))
            (ok true)
          )
        )
      )
    )
  )
)

(define-public (claim-rewards)
  (let ((caller (contract-caller)))
    (let ((pending (pending-rewards caller)))
      (asserts! (> pending u0) err-no-rewards)
      (let ((entry (map-get? stakes { staker: caller })))
        (asserts! (is-some entry) err-no-rewards)
        (let ((info (unwrap-panic entry)))
          (map-set stakes { staker: caller }
            { amount: (get amount info), reward-debt: (/ (* (get amount info) (var-get reward-per-share)) scale), staked-at-block: (get staked-at-block info) }
          )
          (as-contract (stx-transfer? pending (tx-sender) caller))
        )
      )
    )
  )
)

(define-public (add-rewards (amount u128))
  (asserts! (not (var-get staking-paused)) err-staking-paused)
  (asserts! (> amount u0) err-zero-amount)
  (update-reward-per-share amount)
  (ok true)
)

(define-public (set-paused (paused bool))
  (asserts! (is-eq (contract-caller) (get-owner)) err-owner-only)
  (var-set staking-paused paused)
  (ok true)
)

(define-public (set-owner (new-owner principal))
  (asserts! (is-eq (contract-caller) (get-owner)) err-owner-only)
  (var-set owner (some new-owner))
  (ok true)
)

(define-read-only (get-stake (staker principal)) (map-get? stakes { staker: staker }))
(define-read-only (get-pending-rewards (staker principal)) (ok (pending-rewards staker)))
(define-read-only (get-total-staked) (var-get total-staked))
(define-read-only (get-config)
  (ok { min-stake: min-stake-amount, lock-period: lock-period, staking-paused: (var-get staking-paused), owner: (get-owner), reward-per-share: (var-get reward-per-share), total-rewards-added: (var-get total-rewards-added) })
)
